name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build release binary
        run: cargo build --release

      # Linux/macOS artifact naming (bash)
      - name: Prepare artifact name and path (Linux/macOS)
        if: runner.os != 'Windows'
        id: artifact_unix
        shell: bash
        run: |
          BIN_NAME="bake-tool"
          EXT=""
          ARTIFACT_NAME="${BIN_NAME}-${{ matrix.os }}${EXT}"
          ARTIFACT_PATH="target/release/${BIN_NAME}${EXT}"
          echo "name=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
          echo "path=$ARTIFACT_PATH" >> $GITHUB_OUTPUT

      - name: Prepare artifact name and path (Windows)
        if: runner.os == 'Windows'
        id: artifact_windows
        shell: pwsh
        run: |
          $BIN_NAME = "bake-tool"
          $EXT = ".exe"
          $ARTIFACT_NAME = "$BIN_NAME-$( $env:RUNNER_OS )$EXT"
          $ARTIFACT_PATH = "target/release/$BIN_NAME$EXT"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "name=$ARTIFACT_NAME"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "path=$ARTIFACT_PATH"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact.outputs.name }}
          path: ${{ steps.artifact.outputs.path }}
